payment_intent_url = 'https://api.paymongo.com/v1/payment_intents'
payment_method_url = 'https://api.paymongo.com/v1/payment_methods'
payment_source_url = 'https://api.paymongo.com/v1/sources'
payment_url = 'https://api.paymongo.com/v1/payments'
hook_url = 'https://api.paymongo.com/v1/webhooks'